
language: php
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - php5
    - php5-redis
    - php5-gd 
    - php5-mysql
php: 
  - '5.6'
services:
  - redis-server
  - mysql
before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - composer install
  - mysql -u root -e 'create database dark_launch;'
  - vendor/bin/phinx migrate -c config-phinx-travis-ci.php
script:
  - vendor/bin/phpunit --coverage-text

