version: '2'
services:
  dark-launch-library:
    build: .
    volumes:
     - .:/home/app/code
     - ~/.ssh:/home/app/.ssh
    environment:
     - USER_NAME=app
    container_name: dark-launch-library
